let adminAuthorizedPages = [
  'root',
  'members-list',
  'web-designs-list',
  'web-design',
  'seo-programs-list',
  'seo-program',
  'google-ads-programs',
  'google-ads-program',
  'team',
  'milestones',
  'calendar',
  'files',
  'chat',
  'add-project-tasks',
  'tasks',
  'account-setting',
  'payment-setting',
  'roles-setting',
  'bucks-setting',
  'view-received-notifications',
  'view-project-activities',
  'manage-templates',
  'marketplace-service',
]

export default adminAuthorizedPages
